#include "splity.h"
#include "sendstring_dvorak.h"

enum layer_names {
	_DVORAK,
	_NUMPAD,
	_CODING,
	_FROW,
	_GAMING
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_DVORAK] = LAYOUT(
	DV_QUOT,	DV_COMM, 	DV_DOT, 	DV_P, 		DV_Y, 		DV_F, 		DV_G, 		DV_C, 		DV_R, 		DV_L,
	DV_A,		LCTL_T(DV_O),	LSFT_L(DV_E), 	DV_U, 		DV_I, 		DV_D, 		LSFT_T(DV_H), 	LCTL_T(DV_T), 	DV_N, 		DV_S,
	DV_SCLN, 	DV_Q, 		DV_J, 		DV_K, 		DV_X, 		DV_B, 		DV_M, 		DV_W, 		DV_V, 		DV_Z,
			MO(_CODE), 	KC_BSPC, 	MO(_NUMPAD),	KC_ENT,     	KC_TAB,		KC_LGUI,	KC_SPC,		TO(_GAMING)
),


    [_NUMPAD] = LAYOUT(
	KC_PSLS, 	KC_7, 		KC_8, 		KC_9, 		KC_PAST, 	KC_MPLY,	KC_MPRV, 	KC_UP, 		KC_MNXT,	KC_TRNS,
	KC_LSFT, 	KC_4, 		KC_5, 		KC_6, 		KC_PPLS, 	KC_TRNS, 	KC_LEFT,	KC_DOWN,	KC_RGHT,	KC_LCTL,
	KC_0, 		KC_1, 		KC_2, 		KC_3, 		KC_PMNS, 	KC_TRNS, 	KC_EXLM, 	KC_CIRC, 	KC_PERC, 	KC_TRNS,
			KC_NO,		KC_NO,		KC_NO,		KC_NO, 		KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS
),

    [_CODING] = LAYOUT(
	KC_TRNS, 	LSFT(DV_BSLS), 	KC_F5,		DV_GRAVE, 	DV_AT,	 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS,
	DV_QUES, 	DV_HASH, 	DV_LPRN, 	DV_RPRN, 	KC_UNDS, 	KC_TRNS, 	DV_TRNS, 	KC_TRNS, 	KC_TRNS,	KC_TRNS,
	KC_LSFT,	DV_DLR, 	DV_LBRC, 	DV_RBRC, 	KC_PEQL, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS,
			KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS,	KC_TRNS, 	KC_TRNS, 	KC_DEL
),


    [_FROW] = LAYOUT(
    	KC_F1, 	   	KC_F2, 		KC_F3, 		KC_F4, 		KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS,
	KC_F5,  	KC_F6, 		KC_F7, 		KC_F8, 		KC_TRNS,   	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS,
	KC_F9, 	   	KC_F10, 	KC_F11, 	KC_F12, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS,
		        KC_TRNS,	KC_TRNS,      	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS
),

    [_GAMING] = LAYOUT(
	KC_TAB, 	DV_Q, 		DV_W, 		DV_E, 		DV_R, 		KC_TRNS, 	KC_BTN1,	KC_MS_U, 	KC_BTN2,	KC_BTN3,
	KC_LSFT, 	DV_A, 		DV_S, 		DV_D, 		DV_F, 		KC_TRNS, 	KC_MS_L,	KC_MS_D,	KC_MS_R,	KC_TRNS,
	KC_LCTL, 	DV_Z, 		DV_X, 		DV_C, 		DV_V, 		KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	KC_TRNS,
			DV_1, 		KC_SPC,     	DV_2, 		DV_3, 		KC_TRNS, 	KC_TRNS, 	KC_TRNS, 	TO(_DVORAK)
)

};
